version: "3.8"

volumes:
  public_volume:

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      target: production
    volumes:
      - ./log:/var/log
      - public_volume:/var/www/html/public
    environment:
      - APP_ENV=production
      - APP_NAME=Okitama
      - APP_KEY=base64:FybbGVQEZfzWe2p7sUwjCiIz3yg/h+PsI/N+1/iCww4=
      - APP_URL=http://localhost
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=project
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - SESSION_DRIVER=cookie
      - SANCTUM_STATEFUL_DOMAINS=localhost
      - SESSION_DOMAIN=localhost

  web:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      args:
        - UPSTREAM_NAME=app
        - FPM_PORT=9000
    ports:
      - "${WEB}:80"
    volumes:
      - public_volume:/var/www/html/public
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: "Asia/Tokyo"
      # 文字コード指定
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "${DB}:3306"
