version: "3.8"

volumes:
  vendor-store:
  node_modules-store:

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        - ENVIRONMENT=production
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/app

  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      args:
        - UPSTREAM_NAME=localhost
        - FPM_PORT=9000
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/web
